--create db
CREATE DATABASE carsPDO
    DEFAULT CHARACTER SET = 'utf8mb4';

ALTER TABLE cars_audit DROP FOREIGN KEY IF EXISTS cars_audit_ibfk_1;

DROP TABLE IF EXISTS cars_audit;

DROP TABLE IF EXISTS carsPDO;

CREATE TABLE carsPDO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255) NULL
);

CREATE TABLE cars_audit (
    audit_id INT AUTO_INCREMENT PRIMARY KEY,
    car_id INT NOT NULL,
    old_brand VARCHAR(255) NOT NULL,
    new_brand VARCHAR(255) NOT NULL,
    old_model VARCHAR(255) NOT NULL,
    new_model VARCHAR(255) NOT NULL,
    old_price DECIMAL(10, 2) NOT NULL,
    new_price DECIMAL(10, 2) NOT NULL,
    cars_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (car_id) REFERENCES carsPDO(id) ON DELETE CASCADE
);